apiVersion: v1
kind: Service
metadata:
  name: qc-monolith-svc
  labels:
    app: qc-monolith
spec:
  type: LoadBalancer
  selector:
    app: qc-monolith
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
